'use strict';
const B=Builder, E=B.esc, KEY='wumpus-builder-'+CONFIG.edition+'-v1';
let state,week,day,page='',timerHandle,toastHandle,cameraStream,cameraHandle,foodDate=B.dateKey();
let bootWarning='',existingRaw=null;
try{existingRaw=localStorage.getItem(KEY);state=existingRaw?B.validate(JSON.parse(existingRaw),BAMF):B.fresh();}catch(e){state=B.fresh();bootWarning='Existing data could not be read. It has not been overwritten. Restore a backup in Settings.';}
function seedDemo(){
 const now=new Date();now.setDate(now.getDate()-14);state.start=B.dateKey(now);
 for(let w=1;w<=2;w++)for(let d=0;d<6;d++){const date=new Date(now);date.setDate(now.getDate()+(w-1)*7+d);state.sessions[`${state.run}:${w}:${d}`]={name:BAMF[d].name,week:w,day:d,date:B.dateKey(date),complete:true,exercises:BAMF[d].exercises.map(e=>({name:e.name,sets:Array.from({length:B.count(e.weeks[w-1])},()=>({kg:/bench press/i.test(e.name)?50+(w-1)*5:/squat/i.test(e.name)?60+(w-1)*5:0,reps:10,done:true}))}))};}
 state.weights=[{date:state.start,kg:86},{date:B.dateKey(),kg:85.5}];
 state.logs[B.dateKey()]=READY_RECIPES.breakfast.foods.map(id=>({...READY_FOODS.find(f=>f.id===id),qty:1,id:crypto.randomUUID(),meal:'Morning'}));
}
if(CONFIG.edition==='demo'&&!existingRaw&&!bootWarning)seedDemo();
({week,day}=B.schedule(state.start));
const $=id=>document.getElementById(id);
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastHandle);toastHandle=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function persist(next=state){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;bootWarning='';existingRaw=null;return true;}catch(e){toast('Storage is full or unavailable. Export a backup before continuing. This change was not saved.');return false;}}
function change(fn){const next=structuredClone(state);fn(next);return persist(next);}
function modal(html){stopCamera();$('modal-content').innerHTML=html;$('modal').showModal();}
function closeModal(){stopCamera();$('modal').close();}
function foods(){return [...READY_FOODS.map(f=>state.foods.find(x=>x.id===f.id)||f),...state.foods.filter(f=>!READY_FOODS.some(x=>x.id===f.id))];}
function programDays(){return state.custom?.days||BAMF;}
function programName(){return state.custom?.name||'BAMF Builder';}
function sessions(){return Object.entries(state.sessions).filter(([k])=>k.startsWith(state.run+':')).map(([,v])=>v);}
function completed(){return sessions().filter(s=>s.complete).length;}
function recipeFoods(id){return READY_RECIPES[id].foods.map(id=>foods().find(f=>f.id===id));}
function known(f){return ['c','p','carb','f'].every(k=>B.numeric(f[k]));}
function fmt(n){return Math.round(n).toLocaleString();}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function backup(){download(`wumpus-${CONFIG.edition}-${B.dateKey()}.json`,JSON.stringify(state,null,2));toast('Backup downloaded. Keep it somewhere safe.');}
function head(kicker,title,sub=''){return `<div class="page-title"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><button class="quiet" data-action="settings">Settings</button></div>`;}
function stat(label,val,detail){return `<div class="stat"><small>${label}</small><b>${val}</b><small>${detail}</small></div>`;}
function shop(){const products=[{name:'Original Buck Feed',kind:'Protein powder',url:'https://www.buckedup.com/buck-feed-original-protein'},{name:'Creatine Monohydrate',kind:'Creatine powder',url:'https://www.buckedup.com/creatine-monohydrate'},{name:'Bucked Up Pre-Workout',kind:'Pre-workout supplement',url:'https://www.buckedup.com/shop/preworkout/pre-workout-supplement'}];return `<section class="card space"><div class="card-head"><div><div class="eyebrow">Bucked Up ambassador</div><h2 class="space">Shop through HyperWumpus</h2></div><button class="quiet tiny" data-action="copy-code">HYPER1 · Copy</button></div><p>Ambassador disclosure: I may earn a commission from eligible purchases made through my store link or code.</p><div class="actions space"><a class="button" href="https://bckd.co/Ks6tlzm" target="_blank" rel="noopener sponsored">Shop with my ambassador link ↗</a><a class="button quiet" href="https://www.buckedupbootcamp.com/" target="_blank" rel="noopener">Bootcamp requirements ↗</a></div><div class="food-grid space">${products.map(p=>`<div class="card"><small>${p.kind}</small><h3 class="space">${p.name}</h3><div class="actions space"><a class="button quiet" href="${p.url}" target="_blank" rel="noopener">Product details ↗</a><a class="button quiet tiny" href="https://bckd.co/Ks6tlzm" target="_blank" rel="noopener sponsored">Shop via my store ↗</a></div></div>`).join('')}</div><small class="space" style="display:block">Product-detail links are ordinary Bucked Up links. To support this creator, use the ambassador store link or enter HYPER1 at checkout. Current offers and eligibility are determined by Bucked Up.</small><details class="space"><summary>About Bootcamp purchases</summary><p>The official challenge lists one full-sized Bucked Up supplement purchase as part of prize eligibility. Purchases can be made through Bucked Up or an official retail store; using my link is optional. Use the same email as your challenge registration when checking out. Buying something does not replace the official photo and survey requirements.</p><a class="pill" href="https://www.buckedupbootcamp.com/" target="_blank" rel="noopener">Read the official requirements ↗</a></details></section>`;}
function footer(){return `<footer>Independent HyperWumpus companion. Partnership proposal; no official app affiliation is implied.<br>Food estimates vary by portion and brand. <a href="https://world.openfoodfacts.org" target="_blank" rel="noopener">Barcode data: Open Food Facts (ODbL)</a>. Your records stay in this browser. Export regularly.</footer>`;}
async function lookupFood(code){
 const fields='product_name,brands,serving_size,nutriments';
 const url=CONFIG.staticHosting?`https://world.openfoodfacts.org/api/v2/product/${code}.json?fields=${fields}&app_name=WumpusBuilder`:'/api/product/'+code;
 const response=await fetch(url,{signal:AbortSignal.timeout(16000)});
 if(!response.ok)throw Error(response.status===404?'No food found. Enter the label manually.':'Food lookup unavailable. Enter the label manually.');
 const data=await response.json();
 if(!CONFIG.staticHosting)return data;
 if(data.status!==1||!data.product)throw Error('No food found. Enter the label manually.');
 const p=data.product;return {name:p.product_name||'Unnamed food',brand:p.brands||'',servingSize:p.serving_size||'',nutriments:p.nutriments||{}};
}
function today(){const s=B.schedule(state.start),work=programDays()[s.day],logs=state.logs[B.dateKey()]||[],m=B.macros(logs);return `
 <div class="hero"><div class="hero-copy"><div class="eyebrow">Your next chapter · week ${s.week} / 8</div><h1>Show up.<br><em>Build again.</em></h1><p>Your workout is ready. Your usual meals are one tap away. Start with the next small thing.</p><div class="actions"><a class="button" href="#train" data-action="today-workout">${work.exercises.length?'Start today’s workout':'View recovery day'} ↗</a><a class="button quiet" href="#fuel">Log a meal</a></div></div><img class="hero-art" src="assets/hero.png" alt="Cyber Wumpy with glowing antlers and a shaker"></div>
 ${s.finished?'<div class="notice">Eight weeks have passed. Finish outstanding sessions or archive this run in Settings and begin again.</div>':''}${s.upcoming?'<div class="notice">Your start date is in the future. You can browse Week 1 now.</div>':''}
 <div class="stats">${stat('Sessions complete',`${completed()} <span>/ ${programDays().filter(d=>d.exercises.length).length*8}</span>`,'This challenge')}${stat('Today’s protein',`${fmt(m.p)} <span>g</span>`,state.targets.p?`Your target: ${E(state.targets.p)} g`:'Set your own target in Settings')}${stat('Food logged',`${fmt(m.c)} <span>kcal</span>`,state.targets.c?`Your target: ${E(state.targets.c)} kcal`:'Today’s recorded food')}</div>
 <div class="grid"><section class="card"><div class="card-head"><h2>One session at a time</h2><span class="pill green">${s.day===6?'Recovery':'Day '+(s.day+1)}</span></div><h3>${E(work.name)}</h3><p class="space">${work.exercises.length+' movements'} · ${E(programName())}</p><div class="track"><i style="width:${Math.min(100,completed()/Math.max(1,programDays().filter(d=>d.exercises.length).length*8)*100)}%"></i></div><small>Progress comes from the sessions you log.</small><div class="space"><a class="button quiet" href="#train" data-action="today-workout">Open workout</a></div></section>
 <section class="card"><div class="card-head"><h2>Fuel on autopilot</h2><a class="pill" href="#fuel">All meals ↗</a></div>${['breakfast','chickenRice','yogurt'].map(id=>`<div class="list-row"><div><h3>${E(READY_RECIPES[id].name)}</h3><small>${fmt(B.macros(recipeFoods(id)).p)} g protein · estimated</small></div><button class="quiet tiny" data-action="meal" data-id="${id}">Log</button></div>`).join('')}</section></div>
 <div class="notice">Next check-in: record your body weight or a private progress photo. Official Bootcamp submissions still belong in their portal.</div>`;}
function sessionFor(create=false){const key=`${state.run}:${week}:${day}`,existing=state.sessions[key];if(existing)return existing;const d=programDays()[day],scheduled=new Date(state.start+'T12:00:00');scheduled.setDate(scheduled.getDate()+(week-1)*7+day);const s={name:d.name,week,day,date:B.dateKey(scheduled),complete:false,exercises:d.exercises.map(e=>({name:e.name,sets:Array.from({length:B.count(e.weeks[week-1])},()=>({kg:0,reps:0,done:false}))}))};if(create)change(n=>n.sessions[key]=s);return s;}
function train(){const d=programDays()[day],s=sessionFor();return `${head(E(programName()),'Ready when you are.','Prescriptions change with the week. Log the work you actually do.')}
 <div class="week-strip" aria-label="Select week">${Array.from({length:8},(_,i)=>`<button data-action="week" data-id="${i+1}" class="${week===i+1?'selected':''}" aria-pressed="${week===i+1}">Week ${i+1}</button>`).join('')}</div>
 <div class="day-strip" aria-label="Select workout">${programDays().map((d,i)=>`<button data-action="day" data-id="${i}" class="${day===i?'selected':''}" aria-pressed="${day===i}"><b>${i===6?'Rest':'Day '+(i+1)}</b>${E(d.name)}</button>`).join('')}</div>
 <div class="card-head"><h2>${E(d.name)}</h2><div class="actions"><span class="pill">${state.unit}</span><button class="quiet tiny" data-action="rest">90s rest</button></div></div>
 ${!d.exercises.length?'<div class="card empty">Recovery day. There are no prescribed exercises today. You can record a check-in on Progress.</div>':''}
 ${d.exercises.map((e,i)=>`<section class="exercise"><div class="exercise-title"><h3>${E(e.name)}</h3><span class="prescription">${E(e.weeks[week-1]||'Prescription unspecified')}</span></div>${e.note?`<p>${E(e.note)}</p>`:''}${!e.weeks[week-1]?'<p>No sets/reps were supplied. A blank logging row is available; confirm your prescription before training.</p>':''}<div class="set-row set-head"><span>Set</span><span>Weight (${state.unit})</span><span>${/minute/.test(e.weeks[week-1]||'')?'Time (minutes)':'Reps / time as noted'}</span><span>Done</span></div>${s.exercises[i].sets.map((set,j)=>`<div class="set-row ${set.done?'completed':''}"><small>${j+1}</small><input type="number" min="0" max="5000" step="0.5" inputmode="decimal" aria-label="${E(e.name)} set ${j+1} weight" data-set="${i}:${j}:kg" value="${set.kg?B.display(set.kg,state.unit):''}" placeholder="—"><input type="number" min="0" max="10000" step="0.1" inputmode="decimal" aria-label="${E(e.name)} set ${j+1} reps or duration" data-set="${i}:${j}:reps" value="${set.reps||''}" placeholder="—"><input type="checkbox" aria-label="${E(e.name)} set ${j+1} done" data-set="${i}:${j}:done" ${set.done?'checked':''}></div>`).join('')}<div class="space"><button class="quiet tiny" data-action="add-set" data-id="${i}">+ Logging row</button></div></section>`).join('')}
 ${d.exercises.length?`<div class="actions"><button data-action="finish">${s.complete?'Reopen this session':'Finish session'}</button><span class="pill">${s.exercises.flatMap(e=>e.sets).filter(x=>x.done).length} sets checked</span></div>`:''}<div class="notice">Weights are stored in kilograms internally and converted when you change units. Logging a past session does not count as today’s workout.</div>`;}
function fuel(){const logs=state.logs[foodDate]||[],m=B.macros(logs);return `${head('Less deciding. More doing.','Your usual fuel.','Repeat the meals that fit your day. Adjust portions before logging.')}<label style="max-width:220px">Food diary date<input id="food-date" type="date" value="${foodDate}" required></label><div class="stats">${stat('Calories',`${fmt(m.c)} <span>kcal</span>`,'Logged on selected date')}${stat('Protein',`${fmt(m.p)} <span>g</span>`,'Logged on selected date')}${stat('Carbs / fat',`${fmt(m.carb)} <span>/ ${fmt(m.f)} g</span>`,'Logged on selected date')}</div>
 <div class="meal-grid">${READY_MEALS.map(slot=>`<section class="card meal-card"><div class="eyebrow">${E(slot.name)}</div><select aria-label="${E(slot.name)} recipe" id="recipe-${slot.id}">${slot.choices.map(id=>`<option value="${id}" ${id===slot.defaultRecipe?'selected':''}>${E(READY_RECIPES[id].name)}</option>`).join('')}</select><p id="prep-${slot.id}">${E(READY_RECIPES[slot.defaultRecipe].prep)}</p><div class="macro-line">Saved defaults · editable portions</div><button data-action="slot" data-id="${slot.id}">Log this meal +</button></section>`).join('')}</div>
 <section class="card space"><div class="card-head"><h2>Something else?</h2><button class="quiet tiny" data-action="custom-food">+ Save a food</button></div><div class="actions"><button class="quiet" data-action="barcode">Scan / enter barcode</button><button class="quiet" data-action="water">Water check-in</button></div><small class="space" style="display:block">Snacks fit here too. Log a portion and carry on.</small><div class="food-grid space">${foods().map(f=>`<button class="food-chip" data-action="food" data-id="${E(f.id)}">${E(f.name)}<small>${f.requiresLabel&&!known(f)?'Save your label first':fmt(f.c)+' kcal · '+fmt(f.p)+' g protein'}</small></button>`).join('')}</div></section>
 <section class="card space"><div class="card-head"><h2>Food diary</h2><span class="pill">${foodDate}</span></div>${logs.length?logs.map(f=>`<div class="list-row"><div><h3>${E(f.name)}</h3><small>${E(f.meal)} · ${E(f.qty)} × ${E(f.portion)} · ${fmt(f.c*f.qty)} kcal / ${fmt(f.p*f.qty)} g protein</small></div><button class="quiet tiny" data-action="delete-food" data-id="${E(f.id)}" aria-label="Remove ${E(f.name)}">Remove</button></div>`).join(''):'<p class="empty">Nothing logged yet. Start with your usual breakfast or a shake.</p>'}</section>`;}
function progress(){const ss=sessions().filter(s=>s.complete),all=sessions();const best=new Map();for(const s of all)for(const e of s.exercises)for(const set of e.sets)if(set.done&&set.kg>0){const prev=best.get(e.name);if(!prev||set.kg>prev.kg)best.set(e.name,set);}
 const counts=Array.from({length:8},(_,i)=>ss.filter(s=>s.week===i+1).length);
 return `${head('Proof, one day at a time.','Look how far.','Your logged work, not a score or a punishment.')}<div class="stats">${stat('Sessions complete',ss.length,'Current run')}${stat('Sets logged',all.flatMap(s=>s.exercises.flatMap(e=>e.sets)).filter(s=>s.done).length,'Current run')}${stat('Latest weight',state.weights.length?`${B.display(state.weights.at(-1).kg,state.unit)} <span>${state.unit}</span>`:'—','Optional check-in')}</div><div class="grid"><section class="card"><h2>Eight weeks of showing up</h2><div class="bars">${counts.map((n,i)=>`<div class="bar-wrap"><small>${n}</small><div class="bar" style="height:${Math.max(3,n*17)}px"></div><small>W${i+1}</small></div>`).join('')}</div><small>Completed sessions per week</small></section><section class="card"><h2>Strength records</h2>${[...best].slice(0,8).map(([name,s])=>`<div class="list-row"><div><h3>${E(name)}</h3><small>Heaviest logged set · ${E(s.reps)} reps / duration</small></div><strong>${B.display(s.kg,state.unit)} ${state.unit}</strong></div>`).join('')||'<p class="empty">Check off a weighted set to start your record.</p>'}</section></div>
 <section class="card space"><div class="card-head"><h2>Your private check-ins</h2><span class="pill">This browser only</span></div><div class="actions"><button data-action="weight">Log body weight</button><button class="quiet" data-action="photo">Add progress photo</button><button class="quiet" data-action="csv">Export workout CSV</button></div><div class="space">${state.weights.slice(-5).map(w=>`<div class="list-row"><span>${E(w.date)}</span><strong>${B.display(w.kg,state.unit)} ${state.unit}</strong></div>`).join('')}</div><div class="photos">${state.photos.map((p,i)=>`<div class="photo"><img src="${p.data}" alt="Private progress check-in ${E(p.date)}"><small>${E(p.date)}</small><button class="quiet tiny" data-action="delete-photo" data-id="${i}">Remove</button></div>`).join('')}</div></section>
 <section class="card space"><h2>Session history</h2>${all.sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<div class="list-row"><div><h3>${E(s.name)}</h3><small>Week ${s.week} · day ${s.day+1} · ${E(s.date)} · ${s.complete?'Complete':'In progress'}</small></div><button class="quiet tiny" data-action="history" data-id="${s.week}:${s.day}">Open</button></div>`).join('')||'<p class="empty">Your first logged set starts the story.</p>'}</section>
 ${state.archives.length?`<section class="card space"><h2>Previous chapters</h2>${state.archives.map(a=>`<div class="list-row"><div><h3>${E(a.name)}</h3><small>${E(a.start)} → ${E(a.end)}</small></div><strong>${Object.values(a.sessions).filter(s=>s.complete).length} sessions</strong></div>`).join('')}</section>`:''}`;}
function premium(){return `<section class="card premium space"><span class="eyebrow">Sponsored access · proposal</span><h2 class="space">More programs. Same simple habit.</h2><p class="space">The proposed next edition adds reviewed program imports, cloud backup, and seasonal program management. Core tracking stays free in this build.</p><div class="premium-grid space"><div><h3>Available now</h3><ul><li>BAMF workout and food tracking</li><li>Personal records and export</li><li>Start a fresh challenge</li></ul></div><div><h3>Planned premium features</h3><ul><li>Reviewed PDF-to-program import</li><li>Multi-program library</li><li>Accounts and cross-device backup</li></ul></div></div><button class="quiet" data-action="premium">View access proposal</button><small class="space" style="display:block">No checkout or subscription is active.</small></section>`;}
function about(){return `${head('A little curiosity. A lot of heart.','Built to begin again.')}<img class="about-banner" src="assets/banner.jpeg" alt="HyperWumpus creator studio banner"><div class="grid"><section class="card"><div class="profile"><img src="assets/avatar.jpeg" alt="HyperWumpus avatar"><div><h2>HyperWumpus</h2><small>Creator · Bucked Up ambassador</small></div></div><p>This project brings workouts and familiar meals into one small daily routine. Follow the journey through training, creativity, and rebuilding consistency.</p><div class="actions space"><a class="button" href="https://www.youtube.com/@HyperWumpus" target="_blank" rel="noopener">Watch the journey ↗</a><a class="button quiet" href="https://hyperwumpus.github.io" target="_blank" rel="noopener">Socials & projects ↗</a></div><small class="space" style="display:block">Following is optional. Everyone can use the core tracker.</small></section><section class="card"><h2>Support the creator</h2><p class="space">Bucked Up ambassador code</p><div class="actions space"><button class="quiet" data-action="copy-code">HYPER1 · Copy</button><a class="button quiet" href="https://bckd.co/Ks6tlzm" target="_blank" rel="noopener sponsored">Visit my store ↗</a></div><small class="space" style="display:block">Ambassador link: I may earn a commission from eligible purchases. Check current offers and exclusions at checkout.</small><div class="notice">This is an independent companion, not the official Bootcamp registration or submission portal.</div><a class="button quiet" href="https://www.buckedupbootcamp.com" target="_blank" rel="noopener">Official Bootcamp ↗</a></section></div>${CONFIG.edition==='public'?premium():`<section class="card space"><h2>${CONFIG.edition==='demo'?'Partnership demonstration':'Your personal chapter'}</h2><p class="space">${CONFIG.edition==='demo'?'Demo records are fictional and stay separate from personal tracking. No testimonials or performance claims are implied.':'Keep the routine small. Your private workout and food records stay on this device.'}</p>${CONFIG.edition==='demo'?'<a class="button space" href="pitch.html">Open partnership pitch ↗</a>':''}</section>`}`;}
function render(){stopCamera();page=location.hash.slice(1);if(!['today','train','fuel','progress','about'].includes(page))page='today';document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('edition').textContent=CONFIG.edition==='demo'?'Demo · fictional records':CONFIG.edition==='public'?'Public · pilot preview':'Personal edition';$('main').innerHTML=`<div class="topline"><span>WUMPUS BUILDER / ${page.toUpperCase()}</span><span>${CONFIG.edition==='demo'?'SAMPLE DATA · ':''}${new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</span></div>${({today,train,fuel,progress,about})[page]()}${CONFIG.edition==='demo'&&['today','about'].includes(page)?shop():''}${footer()}`;document.title=`${page[0].toUpperCase()+page.slice(1)} · Wumpus Builder`;}
function mealDialog(ids,name,meal){const logDate=page==='fuel'?foodDate:B.dateKey();const list=ids.map(id=>foods().find(f=>f.id===id));if(list.some(f=>!known(f))){customFood(list.find(f=>!known(f)));toast('Save the missing label values first, then log this meal.');return;}
 modal(`<h2>${E(name)}</h2><p>Adjust the number of listed portions. These are estimates; package labels take priority.</p><form id="log-meal"><div class="space">${list.map((f,i)=>`<label class="space">${E(f.name)} · ${E(f.portion)}<input name="qty-${i}" type="number" min="0" max="100" step="0.1" value="1" required></label>`).join('')}</div><label class="space">Meal / note<input name="meal" maxlength="80" value="${E(meal)}"></label><button class="space" type="submit">Add to ${logDate===B.dateKey()?'today':logDate}</button></form>`);
 $('log-meal').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),entries=list.map((f,i)=>({...f,qty:Number(fd.get('qty-'+i)),meal:String(fd.get('meal')),id:crypto.randomUUID()})).filter(f=>f.qty>0);if(!entries.length){toast('Choose at least one portion.');return;}if(change(n=>{(n.logs[logDate]??=[]).push(...entries)})){closeModal();render();toast('Meal saved. One less thing to decide.');}};
}
function customFood(food=null,prefill={}){const f=food||prefill;modal(`<h2>${food?'Edit your food label':'Save a familiar food'}</h2><p>Values per portion. Check the package label, including serving size.</p><form id="food-form"><div class="form-grid"><label class="full">Food name<input name="name" required maxlength="120" value="${E(f.name)}"></label><label class="full">Portion / serving size<input name="portion" required maxlength="120" value="${E(f.portion)}" placeholder="1 bar (40 g)"></label>${[['c','Calories (kcal)'],['p','Protein (g)'],['carb','Carbs (g)'],['f','Fat (g)']].map(([k,label])=>`<label>${label}<input name="${k}" type="number" min="0" max="10000" step="0.1" required value="${E(f[k])}"></label>`).join('')}</div><button type="submit">Save label</button></form>`);$('food-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const next={id:food?.id||crypto.randomUUID(),name:String(fd.get('name')),portion:String(fd.get('portion')),requiresLabel:false,c:Number(fd.get('c')),p:Number(fd.get('p')),carb:Number(fd.get('carb')),f:Number(fd.get('f'))};if(change(n=>{n.foods=n.foods.filter(x=>x.id!==next.id);n.foods.push(next)})){closeModal();render();toast('Food saved. Find it under Something else.');}};}
function settings(){modal(`<h2>Your setup</h2><p>Your data stays in this browser. Moving between editions does not copy records.</p>${existingRaw&&bootWarning?'<div class="notice">Unreadable old data detected. Download it before replacing your records.</div><button class="quiet" id="download-unreadable">Download unreadable data</button>':''}<form id="settings-form"><div class="form-grid"><label>Challenge start<input type="date" name="start" value="${E(state.start)}" required></label><label>Weight unit<select name="unit"><option ${state.unit==='lb'?'selected':''}>lb</option><option ${state.unit==='kg'?'selected':''}>kg</option></select></label><label>Daily calories · optional<input type="number" min="0" max="20000" name="c" value="${E(state.targets.c)}" placeholder="Your own target"></label><label>Daily protein (g) · optional<input type="number" min="0" max="1000" name="p" value="${E(state.targets.p)}" placeholder="Your own target"></label><label class="full">Daily calendar reminder<input type="time" name="reminder" value="${E(state.reminder||'18:00')}"></label></div><button type="submit">Save setup</button></form><div class="actions space"><button class="quiet" data-action="backup">Download backup</button><button class="quiet" data-action="calendar">Calendar reminder</button></div><label class="space">Restore a Builder backup<input id="restore-file" type="file" accept=".json,application/json"></label><div class="actions space"><button class="quiet" data-action="import">${CONFIG.edition==='public'?'Program import · planned premium':'Import a workout JSON'}</button><button class="danger" data-action="new-run">Archive & start fresh</button></div>${CONFIG.edition==='demo'?'<button class="quiet space" data-action="reset-demo">Reset fictional demo</button>':''}<small class="space" style="display:block">Calendar reminders require importing the downloaded file into your calendar. The app does not send background notifications.</small>`);
 if(existingRaw&&bootWarning)$('download-unreadable').onclick=()=>download('wumpus-unreadable-backup.json',existingRaw);
 $('settings-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(change(n=>{n.start=String(f.get('start'));n.unit=String(f.get('unit'));n.targets={c:f.get('c'),p:f.get('p')};n.reminder=f.get('reminder')})){({week,day}=B.schedule(state.start));closeModal();render();toast('Setup saved.');}};
 $('restore-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12e6)throw Error('Backup is too large.');const next=B.validate(JSON.parse(await file.text()),BAMF);modal(`<h2>Restore this backup?</h2><p>This replaces this edition’s records: ${Object.keys(next.sessions).length} workout sessions, ${next.foods.length} saved foods, ${next.photos.length} photos. Download your current backup first.</p><div class="actions space"><button class="quiet" id="export-before">Download current backup</button><button id="confirm-restore">Restore backup</button></div>`);$('export-before').onclick=backup;$('confirm-restore').onclick=()=>{if(persist(next)){({week,day}=B.schedule(state.start));closeModal();render();toast('Backup restored.');}};}catch(err){toast(err.message);}};
}
function newRun(){modal(`<h2>Begin a new chapter</h2><p>The current workout run is archived, not deleted. Food logs, saved foods, body weights, and photos remain available. Export a full backup first.</p><div class="actions space"><button id="run-backup" class="quiet">Download backup</button><button id="run-confirm">Archive & begin today</button></div>`);$('run-backup').onclick=backup;$('run-confirm').onclick=()=>{if(change(n=>{n.archives.push({name:programName(),start:n.start,end:B.dateKey(),sessions:structuredClone(n.sessions),custom:n.custom});n.sessions={};n.run=crypto.randomUUID();n.start=B.dateKey()})){week=1;day=0;closeModal();render();toast('Previous chapter archived.');}};}
function importProgram(){if(CONFIG.edition==='public'){premiumInfo();return;}modal(`<h2>Import a workout program</h2><p>Use JSON with a name and up to seven days. Each exercise accepts one prescription or eight weekly prescriptions. PDF import is planned, not enabled.</p><div class="actions space"><button class="quiet" id="template-download">Download example JSON</button></div><label class="space">Program JSON<input id="program-file" type="file" accept=".json,application/json"></label>`);$('template-download').onclick=()=>download('workout-template.json',JSON.stringify({name:'My program',days:[{name:'Full body',exercises:[{name:'Squat',prescription:'3 × 8–10',note:'Your own prescription'}]}]},null,2));$('program-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>250000)throw Error('Program file is too large.');const p=B.program(JSON.parse(await f.text()));modal(`<h2>Review: ${E(p.name)}</h2><p>This starts a new run. Your existing run will be archived.</p>${p.days.map(d=>`<details><summary>${E(d.name)} · ${d.exercises.length} exercises</summary>${d.exercises.map(e=>`<p>${E(e.name)}: ${e.weeks.map((w,i)=>'W'+(i+1)+' '+E(w||'unspecified')).join(' · ')}</p>`).join('')}</details>`).join('')}<button id="apply-program" class="space">Confirm reviewed program</button>`);$('apply-program').onclick=()=>{if(change(n=>{n.archives.push({name:programName(),start:n.start,end:B.dateKey(),sessions:structuredClone(n.sessions),custom:n.custom});n.custom=p;n.sessions={};n.start=B.dateKey();n.run=crypto.randomUUID()})){week=1;day=0;closeModal();location.hash='train';render();toast('Your reviewed program is ready.');}};}catch(err){toast(err.message);}};}
function premiumInfo(){modal('<h2>Sponsored access first.</h2><p>The proposal is for Bucked Up to fund participant access. If a direct paid edition is chosen later, it will need accounts, secure checkout, verified entitlements, and a clear price before launch.</p><div class="notice">No payment is collected here. PDF imports and cloud sync are not enabled in this build.</div>');}
function calendar(){const start=B.dateKey().replaceAll('-',''),time=(state.reminder||'18:00').replace(':','')+'00';const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//HyperWumpus//Builder//EN','BEGIN:VEVENT',`UID:${crypto.randomUUID()}@wumpus-builder`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART:${start}T${time}`,'DURATION:PT15M','RRULE:FREQ=DAILY;COUNT=56','SUMMARY:Wumpus Builder - workout and food check-in','DESCRIPTION:Open your Wumpus Builder tracker.','BEGIN:VALARM','TRIGGER:-PT5M','ACTION:DISPLAY','DESCRIPTION:Your daily check-in','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');download('wumpus-check-in.ics',ics,'text/calendar');toast('Import this file into your calendar to enable reminders.');}
function stopCamera(){if(cameraHandle)clearTimeout(cameraHandle);cameraHandle=null;if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}
function barcodeDialog(){modal('<h2>Scan or enter a barcode</h2><p>Lookups need internet. Camera scanning is available on supporting browsers over HTTPS or localhost. A missing food can always be entered from its label.</p><form id="barcode-form"><label class="space">Barcode<input id="barcode-code" inputmode="numeric" pattern="[0-9]{8,14}" minlength="8" maxlength="14" required></label><div class="actions space"><button id="barcode-lookup" type="submit">Look up food</button><button type="button" id="camera-start" class="quiet">Use camera</button></div></form><video id="camera-video" autoplay playsinline muted hidden></video><div id="lookup-status" class="notice" hidden></div>');
 $('barcode-form').onsubmit=async e=>{e.preventDefault();const code=$('barcode-code').value;if(!/^\d{8,14}$/.test(code))return;const button=$('barcode-lookup'),status=$('lookup-status');button.disabled=true;status.hidden=false;status.textContent='Looking up label…';try{const result=await lookupFood(code);const n=result.nutriments;const basis=['energy-kcal_serving','proteins_serving','carbohydrates_serving','fat_serving'].every(k=>B.numeric(n[k]))?'serving':'100g';const fields=['energy-kcal','proteins','carbohydrates','fat'];const values=fields.map(k=>n[k+'_'+basis]);customFood(null,{name:result.name,portion:basis==='serving'?(result.servingSize||'1 label serving'):'100 g — verify label',c:values[0],p:values[1],carb:values[2],f:values[3]});toast('Review the label values and portion before saving.');}catch(err){status.textContent=err.name==='TimeoutError'?'Lookup timed out. Enter the food manually.':err.message;status.innerHTML=E(status.textContent)+' <button class="quiet tiny" data-action="custom-food">Enter label</button>';}finally{button.disabled=false;}};
 $('camera-start').onclick=async()=>{try{if(!('BarcodeDetector'in window)||!navigator.mediaDevices)throw Error('This browser cannot scan. Type the barcode or enter the label.');const formats=(await BarcodeDetector.getSupportedFormats()).filter(f=>['ean_13','ean_8','upc_a','upc_e'].includes(f));if(!formats.length)throw Error('Food barcode scanning is unavailable in this browser.');stopCamera();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(!$('modal').open||!$('camera-video')){stopCamera();return;}const video=$('camera-video');video.srcObject=cameraStream;video.hidden=false;await video.play();const detector=new BarcodeDetector({formats});const scan=async()=>{if(!cameraStream)return;try{const results=await detector.detect(video);const hit=results.find(r=>/^\d{8,14}$/.test(r.rawValue));if(hit){$('barcode-code').value=hit.rawValue;stopCamera();video.hidden=true;$('barcode-form').requestSubmit();return;}}catch{}cameraHandle=setTimeout(scan,300);};scan();}catch(err){stopCamera();toast(err.message);}};
}
function weightDialog(){modal(`<h2>Body weight check-in</h2><form id="weight-form"><div class="form-grid"><label>Date<input type="date" name="date" value="${B.dateKey()}" required></label><label>Weight (${state.unit})<input type="number" min="1" max="1500" step="0.1" name="weight" required></label></div><button type="submit">Save check-in</button></form>`);$('weight-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);if(change(n=>{n.weights=n.weights.filter(w=>w.date!==fd.get('date'));n.weights.push({date:String(fd.get('date')),kg:B.toKg(fd.get('weight'),n.unit)});n.weights.sort((a,b)=>a.date.localeCompare(b.date))})){closeModal();render();toast('Check-in saved.');}};}
function photoDialog(){modal('<h2>Private progress photo</h2><p>Stored locally and included in your backups. This does not submit your photo to Bootcamp or publish it.</p><label class="space">Choose image<input id="photo-file" type="file" accept="image/jpeg,image/png,image/webp"></label>');$('photo-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Choose JPEG, PNG or WebP.');return;}try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const factor=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*factor);canvas.height=Math.round(bitmap.height*factor);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.75);if(change(n=>n.photos.push({date:B.dateKey(),data}))){closeModal();render();toast('Private photo saved.');}}catch{toast('Image could not be read. Try a smaller image.');}};}
function exportCSV(){const q=s=>'"'+String(s??'').replaceAll('"','""')+'"';const rows=[['Program','Week','Day','Date','Exercise','Set','Weight kg','Reps or duration','Done','Session complete']];for(const s of sessions())for(const e of s.exercises)e.sets.forEach((set,i)=>rows.push([programName(),s.week,s.day+1,s.date,e.name,i+1,set.kg,set.reps,set.done,s.complete]));download('wumpus-workouts.csv',rows.map(r=>r.map(q).join(',')).join('\r\n'),'text/csv');}
function rest(){clearInterval(timerHandle);const until=Date.now()+90000;$('timer').hidden=false;const tick=()=>{const left=Math.max(0,Math.ceil((until-Date.now())/1000));$('timer-value').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(!left){clearInterval(timerHandle);toast('Rest timer complete.');}};tick();timerHandle=setInterval(tick,250);}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const {action,id}=el.dataset;
 switch(action){
 case 'settings':settings();break;case 'backup':backup();break;case 'calendar':calendar();break;case 'import':importProgram();break;case 'new-run':newRun();break;
 case 'today-workout':({week,day}=B.schedule(state.start));if(page==='train')render();break;
 case 'week':week=Number(id);render();break;case 'day':day=Number(id);render();break;
 case 'add-set':{const key=`${state.run}:${week}:${day}`,s=sessionFor();if(s.exercises[Number(id)].sets.length>=20){toast('Maximum 20 logging rows per exercise.');break;}if(change(n=>{n.sessions[key]??=s;n.sessions[key].exercises[Number(id)].sets.push({kg:0,reps:0,done:false})}))render();break;}
 case 'finish':{const s=sessionFor();if(!s.complete&&!s.exercises.some(e=>e.sets.some(x=>x.done))){toast('Check off at least one set before finishing.');break;}if(change(n=>{const key=`${state.run}:${week}:${day}`;n.sessions[key]??=s;n.sessions[key].complete=!s.complete})){render();toast(s.complete?'Session reopened.':'Session saved. You showed up.');}break;}
 case 'rest':rest();break;case 'meal':mealDialog(READY_RECIPES[id].foods,READY_RECIPES[id].name,'Meal');break;
 case 'slot':{const recipe=$('recipe-'+id).value;mealDialog(READY_RECIPES[recipe].foods,READY_RECIPES[recipe].name,READY_MEALS.find(s=>s.id===id).meal);break;}
 case 'food':mealDialog([id],foods().find(f=>f.id===id).name,'Snack');break;
 case 'custom-food':customFood();break;case 'barcode':barcodeDialog();break;
 case 'delete-food':if(change(n=>n.logs[foodDate]=(n.logs[foodDate]||[]).filter(f=>f.id!==id)))render();break;
 case 'water':toast('Water check-in. Keep a bottle within reach.');break;
 case 'weight':weightDialog();break;case 'photo':photoDialog();break;case 'delete-photo':if(change(n=>n.photos.splice(Number(id),1)))render();break;
 case 'csv':exportCSV();break;case 'history':[week,day]=id.split(':').map(Number);location.hash='train';render();break;
 case 'premium':premiumInfo();break;
 case 'copy-code':try{await navigator.clipboard.writeText('HYPER1');toast('HYPER1 copied.');}catch{toast('Your code is HYPER1.');}break;
 case 'reset-demo':modal('<h2>Reset fictional records?</h2><p>This only replaces records in the demo edition.</p><button class="space" id="demo-confirm">Reset demo</button>');$('demo-confirm').onclick=()=>{const previous=state;state=B.fresh();seedDemo();const fresh=state;state=previous;if(persist(fresh)){({week,day}=B.schedule(state.start));closeModal();render();toast('Fictional demo restored.');}};break;
 }
});
document.addEventListener('change',e=>{if(e.target.dataset.set){const [i,j,field]=e.target.dataset.set.split(':'),s=sessionFor(),key=`${state.run}:${week}:${day}`;let value=field==='done'?e.target.checked:Number(e.target.value);if(field!=='done'&&(!Number.isFinite(value)||value<0||value>10000)){toast('Enter a valid non-negative value.');render();return;}if(field==='kg')value=B.toKg(value,state.unit);if(change(n=>{n.sessions[key]??=s;n.sessions[key].exercises[i].sets[j][field]=value})) {if(field==='done')render();}}
 if(e.target.id==='food-date'&&/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)){foodDate=e.target.value;render();}
 if(e.target.id.startsWith('recipe-')){const slot=e.target.id.slice(7);$('prep-'+slot).textContent=READY_RECIPES[e.target.value].prep;}
});
$('settings-open').onclick=settings;$('modal-close').onclick=closeModal;$('modal').addEventListener('close',stopCamera);$('timer-stop').onclick=()=>{clearInterval(timerHandle);$('timer').hidden=true;};
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);$('main').focus({preventScroll:true});});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else render();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
render();if(bootWarning)toast(bootWarning);


